# Generated by Django 5.1.4 on 2025-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='bio_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='tribe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_returned',
            field=models.BooleanField(default=False),
        ),
    ]
