# Generated by Django 5.1.4 on 2025-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poolapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pick",
            name="imty_challenge_winner_pick_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pick",
            name="safe_pick_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pick",
            name="voted_out_pick_correct",
            field=models.BooleanField(default=False),
        ),
    ]
