# Generated by Django 5.1.4 on 2025-09-21 16:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poolapp", "0002_pick_imty_challenge_winner_pick_correct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pick",
            name="parlay",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_immunity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_parlay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_safe",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_vo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_wagers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_week_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="wager_immunity",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="wager_voted_out",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pick",
            name="imty_challenge_winner_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imty_challenge_winner_picks",
                to="poolapp.contestant",
            ),
        ),
        migrations.AlterField(
            model_name="pick",
            name="safe_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safe_picks",
                to="poolapp.contestant",
            ),
        ),
        migrations.AlterField(
            model_name="pick",
            name="voted_out_pick",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voted_out_picks",
                to="poolapp.contestant",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
