# Generated by Django 5.1.4 on 2025-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poolapp", "0005_rename_elimination_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestant",
            name="season",
            field=models.PositiveIntegerField(db_index=True, default=49),
        ),
        migrations.AddField(
            model_name="week",
            name="season",
            field=models.PositiveIntegerField(db_index=True, default=49),
        ),
        migrations.AlterUniqueTogether(
            name="contestant",
            unique_together={("season", "name")},
        ),
    ]
